
CREATE TABLE IF NOT EXISTS posts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    content VARCHAR(1024),
    created_at    TIMESTAMP,
    author   VARCHAR(255)                                 NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);